server:
  port: 8080
spring:
  application:
    name: profile
  data:
    dynamodb:
      entity2ddl:
        auto: create
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,conditions,prometheus
  tracing:
    sampling:
      # All traces should be sent to latency analysis tool
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            # For Exemplars to work we need histogram buckets
            requests: true

# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
springdoc:
  show-actuator: true

# aws configs

amazon:
  aws:
    secretKey: key2
    accessKey: key
  dynamodb:
      endpoint: http://localhost:8000/