name: i18n

on:
  push:
    branches:
      - development
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle build
        run: ./gradlew build

      - uses: pulumi/actions@v4
        stack-name: lysz210/profile/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
